[package]
name = "autoclockspeed"
version = "0.1.3"
edition = "2018"
license = "MIT"
description = " A utility to check stats about your CPU, and auto regulate clock speeds to help with either performance or battery life."
homepage = "https://github.com/JakeRoggenbuck/auto-clock-speed"
repository = "https://github.com/JakeRoggenbuck/auto-clock-speed"
readme = "README.md"
categories = ["command-line-utilities", "hardware-support"]
keywords = ["clockspeed", "cpu", "battery"]

[dependencies]
structopt = { version = "0.3", default-features = false }
regex = "1.5.4"
termion = "1.5.3"
nix = "0.15.0"

[[bin]]
name = "acs"
path = "src/main.rs"
